[maddpg_algorithm]: https://github.com/Brandon-HY-Lin/deep-reinforcement-learning/blob/master/p3_collab-compet/MADDPG/picures/maddpg_algorithm.png "Algorithm of MADDPG"

[maddpg_digram]: https://github.com/Brandon-HY-Lin/deep-reinforcement-learning/blob/master/p3_collab-compet/MADDPG/picures/maddpg_diagram.png "Diagram of MADDPG"


# Abstract

# Introduction
By looking at the highlighted equations in MADDPG algorithm shown below, the major difference between MADDPG and DDPG is the input shape of critic. Note that, x = \[o1, o2, ..., oN\]. The input size of critic in MADDPG algorithm is __(state_size+action_size)*num_agents__. On the other hand, the input size of actor in MADDPG algorithm is the same as DDPG, i.e. __state_size__.

![Algorithm of MADDPG][maddpg_algorithm]

*Algorthm of MADDPG*


Furthermore, the diagram shown below also illustrate this subtile difference.
![Diagram of MADDPG][maddpg_digram]

*Diagram of MADDPG*


In [1]:
import numpy as np

class ActionQuery():
    def __init__(self):
        self.result = None
        

class Game():
    def __init__(self):
        self.players = []
        self.index = 0
        
    def accept(self, player):
        self.players.append(player)
        
        
    def __iter__(self):
        self.index = 0
        return self
    
    
    def __next__(self):
        if self.index < self.__len__():
            player = self.players[self.index]
            self.index += 1
            return player
        else:
            raise StopIteration
    
    
    def __len__(self):
        return len(self.players)
        
        
class Player():
    def __init__(self, game, version):
        self.game = game
        self.version = version
        
        
    def forward_all(self):
        actionQuery = ActionQuery()
        for i_player, player in enumerate(self.game):
            print(i_player)
            player.query(actionQuery)
        
        return actionQuery.result
    
    
    def query(self, actionQuery):
        if actionQuery.result is None:
            actionQuery.result = self.version
        else:
#             actionQuery.result = np.concatenate(actionQuery.result, self.version)
            actionQuery.result = np.concatenate((actionQuery.result, self.version), axis=0)
            
            
game = Game()
player_0 = Player(game, np.array([0, 1]))
player_1 = Player(game, np.array([2, 3]))

game.accept(player_0)
game.accept(player_1)

print(player_0.forward_all())
print(player_0.forward_all())
print(player_0.forward_all())

0
1
[0 1 2 3]
0
1
[0 1 2 3]
0
1
[0 1 2 3]
